version: '3.1'
networks:
        default:
            driver: bridge
            ipam:
                config:
                    - subnet: 10.5.0.0/16
services:
  reverse-proxy:
    container_name: reverse-proxy
    build: ./reverse-proxy/
    ports:
      - 5000:80
    depends_on:
      - keycloak
      - portal-app
      - first-app
      - second-app

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
#      - KEYCLOAK_IMPORT=/tmp/realm_custom.json
#    volumes:
#      - ./realm_custom.json:/tmp/realm_custom.json
    ports:
      - 8081:8080

  portal-app:
      container_name: portal-app
      build: ./portal-app/
      ports:
        - 4000:80
      depends_on:
        - keycloak

  first-app:
      container_name: first-app
      build: ./first-app/
      ports:
        - 4001:80
      depends_on:
        - keycloak

  second-app:
      container_name: second-app
      build: ./second-app/
      ports:
        - 4002:80
      depends_on:
        - keycloak